### ISSUE TITLE
Collect attendees at the top of minutes

### ISSUE THREAD

**Issue by danshearer** [pronovic/hcoop-meetbot#15]
At present if an attendee issues the command **#here** that is recorded as attendance, but otherwise treated in the minutes like any other communication command. That is an incorrect classification, because attendance is administrative, and the code already has a way of handling administrative items.

I propose:

1. In writer.py add ```EventType.ATTENDEE``` to  ```_EXCLUDED[]```

2. In templates/minutes.html, copy the block generated by ```<li py:for="attendee in minutes.attendees">``` to the Prologue, or just before the Prologue.

The advantages of this change are:

* It doesn't matter when someone says "#here", or if they say it multiple times.
* The attendee list is at the top of minutes, where they are normally expected to be.
* It can be very useful (and an improvement on traditional meeting minutes) if you know before reading the body of the minutes who has contributed how many lines.

This additional tiny change would also be good:

* add a percentage next to the linecount for each attendee. This improves the value of the linecount as a team dymanics metric: who is talking the most? Is everyone getting a fair go?

I'm not quite at the "generate a PR" stage because I don't know how to do testing. But I might get there :-)

**Comment by pronovic** [comment]
This seems reasonable to me.  The current behavior is a holdover from the way the original Meetbot worked, and I basically just maintained backwards compatibility.   However, I don't mind moving the attendee list to the top, and I agree that it probably makes more sense to put it there along with the other summary information.   I also think that a linecount percentage should be pretty straightforward to implement (although I haven't given it a lot of thought yet).

**Comment by pronovic** [comment]
@danshearer I released [v0.5.0](https://pypi.org/project/hcoop-meetbot/0.5.0/) with a first pass at this enhancement.  Take a look and see if it meets your needs.  If not, re-open this issue and we can work on a better solution.

**Comment by danshearer** [comment]
Thanks!

The facilities of the 'run' script seem good for testing provided there is a complete developer GitHub setup with commit hooks etc. I wanted to quickly try out your new version without minimum complexity and no GitHub dependency, and I have nearly but not quite succeeded.

My development computer has Limnoria installed and previously had the released hcoop-meetbot via 'pip install', and it works perfectly as a test platform, logging on to test channels at libera. Now I want to do the same thing, only using the 0.5 code.

1. pip uninstall hcoop-meetbot     #to make sure I am using the test code
2. git clone https://github.com/pronovic/hcoop-meetbot ; cd hcoop-meetbot
3. mv localbot localbot.original
4. cp -a /some/place/my-hcoop-conf ./localbot    #this is my working meetbot 0.4 Limnoria config
5. cd localbot; mv HcoopMeetbot.conf localbot.conf   # because ./run expects this name
6. In localbot.conf, change the default username and login channel (eg to #demo-test-hcoop at libera.chat)
7. [ unknown path step, see explanation below]
8. cd .. ; ./run bot

The unknown step is that I don't know how to tell Limnoria to look for the test HcoopMeetbot module when I issue the @loadmodule command.

In Limnoria's [setup.py](https://github.com/progval/Limnoria/blob/5aefd6395fb8cecfca0bec5533e18676d8ae6f07/src/plugin.py#L69), I can see conf.supybot.directories.plugins . I am looking for the config option to append to this path.

**Comment by pronovic** [comment]
One option you can consider is to just open [`tests/fixtures/test_writer/minutes.html`](https://github.com/pronovic/hcoop-meetbot/blob/master/tests/fixtures/test_writer/minutes.html) in a browser.   That file is the expected results for the writer unit tests, so it shows the new location of the attendees section and has example actions with links.

If you want to test for yourself with a live meeting, I think the simplest way is to install v0.5.0 of the plugin globally with `pip install` and then run a brief a meeting in some demo or test channel at libera.chat.

If you would rather use `run bot` against libera.chat instead, then I think that the general process you laid out above should work.  When you execute `run bot`, Poetry takes care of the Python path setup.  It works because you're running all of the code from the same Python virtualenv and because the localbot configuration points Limnoria at the source tree as the location for plugins.  This is what the config option looks like for me in the generated `localbot.conf`:

```
supybot.directories.plugins: /home/pronovic/projects/repos/hcoop-meetbot/src
``` 

I think that if you change that config setting in your own configuration file (the one you're using to replace my `localbot.conf`), Limnoria should find the new version of the plugin from the source tree (`src`).  The value needs to be an absolute path, so change `/home/pronovic/projects/repos/hcoop-meetbot` to wherever you cloned the repo.

**Comment by danshearer** [comment]
``` I think the simplest way is to install v0.5.0 of the plugin globally with pip install``` ok, supposing its a version that you have pushed to pip. Which I see you have, so that's great.

```supybot.directories.plugins: ...````

ah! That is what I was missing. Thanks!

I will report back in a few days.
